chore: update config
chore: remove usless package

chore: remove zsh-nvm plugin

chore: add pnpm

chore: update p10k config

chore: add font for p10k

Revert "chore: add font for p10k"

This reverts commit 67d05e8a4499eac929cd9affa916bcb3fc49d7f8.

chore: add front for p10k

chore: update python

chore: date packages

chore: change docker host

chore: update python

chore: upgrade

chore: fix scripts

chore: update vscode

chore: update deps

chore: fix install kctx failed

chore: update configs

chore: update editor

chore: add backup

chore: add backup

chore: add backup

chore: use volta

chore: support arm64

chore: add install aws session-manager

chore: docker compose config

chore: support vscode

chore: upgrade pkgs

chore: upgrade pkgs

chore: change font to maple mono

chore update configs

chore: update configs

chore: update configs

chore: update configs

chore: update configs

Signed-off-by: Justin CT Liu <justintwd@gmail.com>

diff --git a/scripts/libs/osx b/scripts/libs/osx
--- a/scripts/libs/osx
+++ b/scripts/libs/osx
@@ -7,6 +7,7 @@ setup_osx_gui() {
     echo "command defaults not found"
     return
   fi
+
   defaults write com.apple.finder AppleShowAllFiles YES           # show hidden files
   defaults write com.apple.dock persistent-apps -array            # remove icons in Dock
   defaults write com.apple.dock tilesize -int 72                  # smaller icon sizes in Dock
@@ -42,6 +43,7 @@ install_homebrew() {
     return
   fi
   NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+  eval "$(/opt/homebrew/bin/brew shellenv)"
   brew update
 }
 
@@ -54,16 +56,23 @@ config_sudo() {
 }
 
 config_zsh() {
+  # fix zsh install pip failed
+  mkdir -p "${HOME}/.config/pip"
+  if ! grep -q "break-system-packages = true" "${HOME}/.config/pip/pip.conf"; then
+    echo "[global]" >> "${HOME}/.config/pip/pip.conf"
+    echo "break-system-packages = true" >> "${HOME}/.config/pip/pip.conf"
+  fi
+
   # oh-my-zsh
   rm -rf "${HOME}/.oh-my-zsh"
   wget -qO- https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash || true
 
   # p10k
-  brew install romkatv/powerlevel10k/powerlevel10k
+  brew install powerlevel10k
 
   OUTPUT=$(cat "${HOME}/.zshrc")
   if ! echo "$OUTPUT" | grep -q "powerlevel10k/powerlevel10k.zsh-theme"; then
-    echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >> "${HOME}/.zshrc"
+    echo "source $(brew --prefix)/opt/powerlevel10k/share/powerlevel10k/powerlevel10k.zsh-theme" >> "${HOME}/.zshrc"
   fi
 
   if [[ "$SHELL" != "/bin/zsh" ]]; then
@@ -92,17 +101,47 @@ install_go() {
   source ${HOME}/.gvm/scripts/gvm
 
   OUTPUT=$(gvm list)
-  if echo "$OUTPUT" | grep -q "go1.18"; then
-    echo "go1.18 is already installed."
+  if echo "$OUTPUT" | grep -q "go1.23"; then
+    echo "go1.23 is already installed."
     return
   fi
   brew install go
-  gvm install go1.15.5
-  gvm use go1.15.5 --default
+  # gvm install go1.15.5
+  # gvm use go1.15.5 --default
+  # brew uninstall go
+  # export GOROOT_BOOTSTRAP=${GOROOT}
+  # gvm install go1.18
+  gvm install go1.23
+  gvm use go1.23 --default
   brew uninstall go
-  export GOROOT_BOOTSTRAP=${GOROOT}
-  gvm install go1.18
-  gvm use go1.18 --default
+}
+
+config_docker_compose() {
+  # 設定檔案路徑
+  CONFIG_FILE="$HOME/.docker/config.json"
+  PLUGIN_DIR="/usr/local/lib/docker/cli-plugins"
+
+  # 檢查設定檔案是否存在
+  if [[ ! -f "$CONFIG_FILE" ]]; then
+    # 如果檔案不存在，創建一個基本的 JSON 結構
+    echo '{}' > "$CONFIG_FILE"
+  fi
+
+  # 檢查 cliPluginsExtraDirs 是否已存在
+  if ! jq -e '.cliPluginsExtraDirs' "$CONFIG_FILE" > /dev/null; then
+    # 如果不存在，添加 cliPluginsExtraDirs
+    jq --arg dir "$PLUGIN_DIR" '.cliPluginsExtraDirs = [$dir]' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
+    echo "已添加 cliPluginsExtraDirs: $PLUGIN_DIR"
+  else
+    # 如果已存在，檢查是否已包含該路徑
+    if ! jq -e --arg dir "$PLUGIN_DIR" '.cliPluginsExtraDirs | index($dir)' "$CONFIG_FILE" > /dev/null; then
+      # 如果不包含，將路徑添加到 cliPluginsExtraDirs
+      jq --arg dir "$PLUGIN_DIR" '.cliPluginsExtraDirs += [$dir]' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
+      echo "已將 $PLUGIN_DIR 添加到 cliPluginsExtraDirs"
+    else
+      echo "cliPluginsExtraDirs 已包含 $PLUGIN_DIR"
+    fi
+  fi
 }
 
 mac_app_store_install_applications() {
@@ -137,4 +176,12 @@ install_parallels_desktop() {
   #   return
   # fi
   download_dmg_files https://download.parallels.com/desktop/v15/15.1.5-47309/ParallelsDesktop-15.1.5-47309.dmg
+}
+
+install_session_manager_plugin() {
+  curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac_arm64/sessionmanager-bundle.zip" -o "sessionmanager-bundle.zip"
+  unzip sessionmanager-bundle.zip
+  sudo ./sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
+  sudo rm -rf sessionmanager-bundle.zip
+  sudo rm -rf sessionmanager-bundle
 }
